# Generated by Django 5.0.7 on 2024-08-03 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name_plural': 'Branches'},
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='institution_number',
            new_name='inst_num',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='transit_number',
            new_name='transit_num',
        ),
    ]
